### ISSUE TITLE
Provide llvm 9.0 (master branch) builds?

### ISSUE THREAD

**Issue by oscarbg** [vovkos/llvm-package-travis#1]
similar to request:
https://github.com/vovkos/llvm-package-windows/issues/2
would be nice even if updated with low frequency (say every month or so) as we get only 2 LLVM releases per year.. so would get 6 intermediate releases this way between major releases..

**Comment by vovkos** [comment]
Builds of the LLVM/Clang master branches are now available. Just like with ``llvm-package-windows``, it's X86 plus the two GPU backends on Release builds only.
